# Generated by Django 2.2.19 on 2022-02-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('short_name', models.CharField(max_length=10, verbose_name='короткое наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('ver', models.CharField(max_length=200, unique=True, verbose_name='версия')),
                ('date_begin', models.DateField(verbose_name='дата начала действия справочника')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='код элемента')),
                ('val', models.CharField(max_length=200, verbose_name='значение элемента')),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_book.RBook', verbose_name='родительский идентификатор')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
    ]
