# Generated by Django 2.2.19 on 2022-02-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='reference_book.RBook', verbose_name='родительский идентификатор'),
        ),
        migrations.AlterField(
            model_name='rbook',
            name='ver',
            field=models.CharField(max_length=200, verbose_name='версия'),
        ),
        migrations.AlterUniqueTogether(
            name='rbook',
            unique_together={('name', 'ver')},
        ),
    ]
